import type { LocalizationResource, Appearance } from "@clerk/types"

const commonTexts = {
    signIn: {
        phoneCode: {
            title: 'Periksa telepon Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: 'Kode verifikasi',
            formSubtitle: 'Masukkan kode verifikasi yang dikirim ke nomor telepon Anda',
            resendButton: 'Kirim ulang kode',
        },
    },
} as const;

const localization: LocalizationResource = {
    locale: "id-ID",
    socialButtonsBlockButton: "Lanjutkan dengan {{provider|titleize}}",
    dividerText: "atau",
    formFieldLabel__emailAddress: "Alamat Email",
    formFieldLabel__emailAddresses: 'Alamat Email',
    formFieldLabel__phoneNumber: 'Nomor Telepon',
    formFieldLabel__username: "Nama Pengguna",
    formFieldLabel__emailAddress_phoneNumber: 'Alamat Email atau Nomor Telepon',
    formFieldLabel__emailAddress_username: "Alamat Email atau Nama Pengguna",
    formFieldLabel__phoneNumber_username: 'Nomor Telepon atau Nama Pengguna',
    formFieldLabel__emailAddress_phoneNumber_username: 'Alamat Email, Nomor Telepon, atau Nama Pengguna',
    formFieldLabel__password: "Kata Sandi",
    formFieldLabel__currentPassword: 'Kata Sandi Saat Ini',
    formFieldLabel__newPassword: 'Kata Sandi Baru',
    formFieldLabel__confirmPassword: 'Konfirmasi Kata Sandi',
    formFieldLabel__signOutOfOtherSessions: 'Keluar dari semua perangkat lain',
    formFieldLabel__firstName: "Nama Depan",
    formFieldLabel__lastName: "Nama Belakang",
    formFieldLabel__backupCode: 'Kode Cadangan',
    formFieldInputPlaceholder__emailAddress: '',
    formFieldInputPlaceholder__emailAddresses: 'Masukkan satu atau lebih alamat email, dipisahkan oleh spasi atau koma',
    formFieldInputPlaceholder__phoneNumber: '',
    formFieldInputPlaceholder__username: '',
    formFieldInputPlaceholder__emailAddress_phoneNumber: '',
    formFieldInputPlaceholder__emailAddress_username: '',
    formFieldInputPlaceholder__phoneNumber_username: '',
    formFieldInputPlaceholder__emailAddress_phoneNumber_username: '',
    formFieldInputPlaceholder__password: '',
    formFieldInputPlaceholder__firstName: '',
    formFieldInputPlaceholder__lastName: '',
    formFieldInputPlaceholder__backupCode: '',
    formFieldInputPlaceholder__organizationName: '',
    formFieldInputPlaceholder__organizationSlug: '',
    formFieldError__notMatchingPasswords: `Kata sandi tidak cocok.`,
    formFieldError__matchingPasswords: 'Kata sandi cocok.',
    formFieldAction__forgotPassword: 'Lupa kata sandi?',
    formFieldHintText__optional: "Opsional",
    formButtonPrimary: "Lanjutkan",
    signInEnterPasswordTitle: 'Masukkan kata sandi Anda',
    backButton: 'Kembali',
    footerActionLink__useAnotherMethod: 'Gunakan metode lain',
    badge__primary: 'Utama',
    badge__thisDevice: 'Perangkat ini',
    badge__userDevice: 'Perangkat pengguna',
    badge__otherImpersonatorDevice: 'Perangkat peniru lainnya',
    badge__default: 'Default',
    badge__unverified: 'Belum diverifikasi',
    badge__requiresAction: 'Membutuhkan tindakan',
    badge__you: 'Anda',
    footerPageLink__help: 'Bantuan',
    footerPageLink__privacy: 'Privasi',
    footerPageLink__terms: 'Persyaratan',
    paginationButton__previous: 'Sebelumnya',
    paginationButton__next: 'Berikutnya',
    paginationRowText__displaying: 'Menampilkan',
    paginationRowText__of: 'dari',
    signUp: {
        start: {
            title: "Buat akun baru",
            subtitle: "Daftar menggunakan akun sosial anda atau daftar dengan form untuk melanjutkan.",
            actionText: "Punya akun?",
            actionLink: "Masuk"
        },
        emailLink: {
            title: 'Verifikasi email Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: 'Tautan verifikasi',
            formSubtitle: 'Gunakan tautan verifikasi yang dikirim ke alamat email Anda',
            resendButton: 'Kirim ulang tautan',
            verified: {
                title: 'Berhasil mendaftar',
            },
            loading: {
                title: 'Mendaftar...',
            },
            verifiedSwitchTab: {
                title: 'Email berhasil diverifikasi',
                subtitle: 'Kembali ke tab yang baru dibuka untuk melanjutkan',
                subtitleNewTab: 'Kembali ke tab sebelumnya untuk melanjutkan',
            },
        },
        emailCode: {
            title: 'Verifikasi email Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: 'Kode verifikasi',
            formSubtitle: 'Masukkan kode verifikasi yang dikirim ke alamat email Anda',
            resendButton: 'Kirim ulang kode',
        },
        phoneCode: {
            title: 'Verifikasi nomor telepon Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: 'Kode verifikasi',
            formSubtitle: 'Masukkan kode verifikasi yang dikirim ke nomor telepon Anda',
            resendButton: 'Kirim ulang kode',
        },
        continue: {
            title: 'Isi kolom yang kosong',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            actionText: 'Sudah memiliki akun?',
            actionLink: 'Masuk',
        },
    },
    signIn: {
        start: {
            title: "Masuk",
            subtitle: "Masuk menggunakan akun sosial anda atau masuk dengan form untuk melanjutkan.",
            actionText: "Belum punya akun?",
            actionLink: "Daftar"
        },
        password: {
            title: 'Masukkan kata sandi Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            actionLink: 'Gunakan metode lain',
        },
        forgotPasswordAlternativeMethods: {
            title: 'Lupa Kata Sandi?',
            label__alternativeMethods: 'Atau, masuk dengan metode lain.',
            blockButton__resetPassword: 'Atur ulang kata sandi Anda',
        },
        forgotPassword: {
            title_email: 'Periksa email Anda',
            title_phone: 'Periksa telepon Anda',
            subtitle: 'untuk mengatur ulang kata sandi Anda',
            formTitle: 'Kode pengaturan ulang kata sandi',
            formSubtitle_email: 'Masukkan kode yang dikirim ke alamat email Anda',
            formSubtitle_phone: 'Masukkan kode yang dikirim ke nomor telepon Anda',
            resendButton: 'Kirim ulang kode',
        },
        resetPassword: {
            title: 'Atur Ulang Kata Sandi',
            formButtonPrimary: 'Atur Ulang Kata Sandi',
            successMessage: 'Kata sandi Anda berhasil diubah. Anda akan segera masuk, harap tunggu sebentar.',
        },
        resetPasswordMfa: {
            detailsLabel: 'Kami perlu memverifikasi identitas Anda sebelum mengatur ulang kata sandi Anda.',
        },
        emailCode: {
            title: 'Periksa email Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: 'Kode verifikasi',
            formSubtitle: 'Masukkan kode verifikasi yang dikirim ke alamat email Anda',
            resendButton: 'Kirim ulang kode',
        },
        emailLink: {
            title: 'Periksa email Anda',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: 'Tautan verifikasi',
            formSubtitle: 'Gunakan tautan verifikasi yang dikirim ke email Anda',
            resendButton: 'Kirim ulang tautan',
            unusedTab: {
                title: 'Anda dapat menutup tab ini',
            },
            verified: {
                title: 'Berhasil masuk',
                subtitle: 'Anda akan segera diarahkan',
            },
            verifiedSwitchTab: {
                subtitle: 'Kembali ke tab asli untuk melanjutkan',
                titleNewTab: 'Masuk di tab lain',
                subtitleNewTab: 'Kembali ke tab yang baru dibuka untuk melanjutkan',
            },
            loading: {
                title: 'Masuk...',
                subtitle: 'Anda akan segera diarahkan',
            },
            failed: {
                title: 'Tautan verifikasi ini tidak valid',
                subtitle: 'Kembali ke tab asli untuk melanjutkan.',
            },
            expired: {
                title: 'Tautan verifikasi ini sudah kedaluwarsa',
                subtitle: 'Kembali ke tab asli untuk melanjutkan.',
            },
        },
        phoneCode: { ...commonTexts.signIn.phoneCode },
        phoneCodeMfa: { ...commonTexts.signIn.phoneCode, subtitle: '' },
        totpMfa: {
            title: 'Verifikasi dua langkah',
            subtitle: '',
            formTitle: 'Kode verifikasi',
            formSubtitle: 'Masukkan kode verifikasi yang dihasilkan oleh aplikasi otentikasi Anda',
        },
        backupCodeMfa: {
            title: 'Masukkan kode cadangan',
            subtitle: 'untuk melanjutkan ke {{applicationName}}',
            formTitle: '',
            formSubtitle: '',
        },
        alternativeMethods: {
            title: 'Gunakan metode lain',
            actionLink: 'Dapatkan bantuan',
            blockButton__emailLink: 'Kirim tautan ke {{identifier}} melalui email',
            blockButton__emailCode: 'Kirim kode ke {{identifier}} melalui email',
            blockButton__phoneCode: 'Kirim kode SMS ke {{identifier}}',
            blockButton__password: 'Masuk dengan kata sandi Anda',
            blockButton__totp: 'Gunakan aplikasi otentikasi Anda',
            blockButton__backupCode: 'Gunakan kode cadangan',
            getHelp: {
                title: 'Dapatkan bantuan',
                content: 'Jika Anda mengalami kesulitan masuk ke akun Anda, kirim email kepada kami dan kami akan bekerja dengan Anda untuk mengembalikan akses secepat mungkin.',
                blockButton__emailSupport: 'Dukungan melalui email',
            },
        },
        noAvailableMethods: {
            title: 'Tidak dapat masuk',
            subtitle: 'Terjadi kesalahan',
            message: 'Tidak dapat melanjutkan masuk. Tidak ada faktor otentikasi yang tersedia.',
        },
    },
    userProfile: {
        mobileButton__menu: 'Menu',
        formButtonPrimary__continue: 'Lanjutkan',
        formButtonPrimary__finish: 'Selesai',
        formButtonReset: 'Batal',
        start: {
            headerTitle__account: 'Akun',
            headerTitle__security: 'Keamanan',
            headerSubtitle__account: 'Kelola informasi akun Anda',
            headerSubtitle__security: 'Kelola preferensi keamanan Anda',
            profileSection: {
                title: 'Profil',
            },
            usernameSection: {
                title: 'Nama Pengguna',
                primaryButton__changeUsername: 'Ubah nama pengguna',
                primaryButton__setUsername: 'Atur nama pengguna',
            },
            emailAddressesSection: {
                title: 'Alamat Email',
                primaryButton: 'Tambah alamat email',
                detailsTitle__primary: 'Alamat email utama',
                detailsSubtitle__primary: 'Alamat email ini adalah alamat email utama',
                detailsAction__primary: 'Lengkapi verifikasi',
                detailsTitle__nonPrimary: 'Atur sebagai alamat email utama',
                detailsSubtitle__nonPrimary:
                    'Atur alamat email ini sebagai utama untuk menerima komunikasi terkait akun Anda.',
                detailsAction__nonPrimary: 'Atur sebagai utama',
                detailsTitle__unverified: 'Alamat email belum terverifikasi',
                detailsSubtitle__unverified: 'Alamat email ini belum terverifikasi dan mungkin terbatas dalam fungsionalitasnya',
                detailsAction__unverified: 'Lengkapi verifikasi',
                destructiveActionTitle: 'Hapus',
                destructiveActionSubtitle: 'Hapus alamat email ini dan hapus dari akun Anda',
                destructiveAction: 'Hapus alamat email',
            },
            phoneNumbersSection: {
                title: 'Nomor Telepon',
                primaryButton: 'Tambah nomor telepon',
                detailsTitle__primary: 'Nomor telepon utama',
                detailsSubtitle__primary: 'Nomor telepon ini adalah nomor telepon utama',
                detailsAction__primary: 'Lengkapi verifikasi',
                detailsTitle__nonPrimary: 'Atur sebagai nomor telepon utama',
                detailsSubtitle__nonPrimary:
                    'Atur nomor telepon ini sebagai utama untuk menerima komunikasi terkait akun Anda.',
                detailsAction__nonPrimary: 'Atur sebagai utama',
                detailsTitle__unverified: 'Nomor telepon belum terverifikasi',
                detailsSubtitle__unverified: 'Nomor telepon ini belum terverifikasi dan mungkin terbatas dalam fungsionalitasnya',
                detailsAction__unverified: 'Lengkapi verifikasi',
                destructiveActionTitle: 'Hapus',
                destructiveActionSubtitle: 'Hapus nomor telepon ini dan hapus dari akun Anda',
                destructiveAction: 'Hapus nomor telepon',
            },
            connectedAccountsSection: {
                title: 'Akun Terhubung',
                primaryButton: 'Hubungkan akun',
                title__conectionFailed: 'Hubungan gagal, coba lagi',
                title__connectionFailed: 'Hubungan gagal, coba lagi',
                title__reauthorize: 'Otorisasi ulang diperlukan',
                subtitle__reauthorize:
                    'Lingkup yang diperlukan telah diperbarui, dan Anda mungkin mengalami keterbatasan fungsi. Harap otorisasi ulang aplikasi ini untuk menghindari masalah apa pun',
                actionLabel__conectionFailed: 'Coba lagi',
                actionLabel__connectionFailed: 'Coba lagi',
                actionLabel__reauthorize: 'Otorisasi Sekarang',
                destructiveActionTitle: 'Hapus',
                destructiveActionSubtitle: 'Hapus akun terhubung ini dari akun Anda',
                destructiveActionAccordionSubtitle: 'Hapus akun terhubung',
            },
            passwordSection: {
                title: 'Kata Sandi',
                primaryButton__changePassword: 'Ubah kata sandi',
                primaryButton__setPassword: 'Atur kata sandi',
            },
            mfaSection: {
                title: 'Verifikasi Dua Langkah',
                primaryButton: 'Tambah verifikasi dua langkah',
                phoneCode: {
                    destructiveActionTitle: 'Hapus',
                    destructiveActionSubtitle: 'Hapus nomor telepon ini dari metode verifikasi dua langkah',
                    destructiveActionLabel: 'Hapus nomor telepon',
                    title__default: 'Faktor Default',
                    title__setDefault: 'Atur sebagai Faktor Default',
                    subtitle__default: 'Faktor ini akan digunakan sebagai metode verifikasi dua langkah default saat masuk.',
                    subtitle__setDefault:
                        'Atur faktor ini sebagai faktor default untuk menggunakannya sebagai metode verifikasi dua langkah default saat masuk.',
                    actionLabel__setDefault: 'Atur sebagai default',
                },
                backupCodes: {
                    headerTitle: 'Kode Cadangan',
                    title__regenerate: 'Buat baru kode cadangan',
                    subtitle__regenerate:
                        'Dapatkan set kode cadangan baru yang aman. Kode cadangan sebelumnya akan dihapus dan tidak dapat digunakan.',
                    actionLabel__regenerate: 'Buat kode baru',
                },
                totp: {
                    headerTitle: 'Aplikasi Autentikasi',
                    title: 'Faktor Default',
                    subtitle: 'Faktor ini akan digunakan sebagai metode verifikasi dua langkah default saat masuk.',
                    destructiveActionTitle: 'Hapus',
                    destructiveActionSubtitle: 'Hapus aplikasi autentikasi dari metode verifikasi dua langkah',
                    destructiveActionLabel: 'Hapus aplikasi autentikasi',
                },
            },
            activeDevicesSection: {
                title: 'Perangkat Aktif',
                primaryButton: 'Perangkat Aktif',
                detailsTitle: 'Perangkat saat ini',
                detailsSubtitle: 'Ini adalah perangkat yang sedang Anda gunakan saat ini',
                destructiveActionTitle: 'Keluar',
                destructiveActionSubtitle: 'Keluar dari akun Anda pada perangkat ini',
                destructiveAction: 'Keluar dari perangkat',
            },
            web3WalletsSection: {
                title: 'Dompet Web3',
                primaryButton: 'Dompet Web3',
                destructiveActionTitle: 'Hapus',
                destructiveActionSubtitle: 'Hapus dompet web3 ini dari akun Anda',
                destructiveAction: 'Hapus dompet',
            },
        },
        profilePage: {
            title: 'Perbarui profil',
            imageFormTitle: 'Gambar profil',
            imageFormSubtitle: 'Unggah gambar',
            imageFormDestructiveActionSubtitle: 'Hapus gambar',
            fileDropAreaTitle: 'Seret file ke sini, atau...',
            fileDropAreaAction: 'Pilih file',
            fileDropAreaHint: 'Unggah gambar JPG, PNG, GIF, atau WEBP yang ukurannya kurang dari 10 MB',
            successMessage: 'Profil Anda telah diperbarui.',
        },
        usernamePage: {
            title: 'Perbarui nama pengguna',
            successMessage: 'Nama pengguna Anda telah diperbarui.',
        },
        emailAddressPage: {
            title: 'Tambahkan alamat email',
            emailCode: {
                formHint: 'Sebuah email yang berisi kode verifikasi akan dikirim ke alamat email ini.',
                formTitle: 'Kode verifikasi',
                formSubtitle: 'Masukkan kode verifikasi yang dikirimkan ke {{identifier}}',
                resendButton: 'Kirim ulang kode',
                successMessage: 'Email {{identifier}} telah ditambahkan ke akun Anda.',
            },
            emailLink: {
                formHint: 'Sebuah email yang berisi tautan verifikasi akan dikirim ke alamat email ini.',
                formTitle: 'Tautan verifikasi',
                formSubtitle: 'Klik tautan verifikasi dalam email yang dikirimkan ke {{identifier}}',
                resendButton: 'Kirim ulang tautan',
                successMessage: 'Email {{identifier}} telah ditambahkan ke akun Anda.',
            },
            removeResource: {
                title: 'Hapus alamat email',
                messageLine1: '{{identifier}} akan dihapus dari akun ini.',
                messageLine2: 'Anda tidak akan bisa masuk menggunakan alamat email ini lagi.',
                successMessage: '{{emailAddress}} telah dihapus dari akun Anda.',
            },
        },
        phoneNumberPage: {
            title: 'Tambahkan nomor telepon',
            successMessage: '{{identifier}} telah ditambahkan ke akun Anda.',
            infoText: 'Sebuah pesan teks yang berisi tautan verifikasi akan dikirim ke nomor telepon ini.',
            infoText__secondary: 'Biaya pesan dan data mungkin berlaku.',
            removeResource: {
                title: 'Hapus nomor telepon',
                messageLine1: '{{identifier}} akan dihapus dari akun ini.',
                messageLine2: 'Anda tidak akan bisa masuk menggunakan nomor telepon ini lagi.',
                successMessage: '{{phoneNumber}} telah dihapus dari akun Anda.',
            },
        },
        connectedAccountPage: {
            title: 'Tambahkan akun terhubung',
            formHint: 'Pilih penyedia untuk menghubungkan akun Anda.',
            formHint__noAccounts: 'Tidak ada penyedia akun eksternal yang tersedia.',
            socialButtonsBlockButton: 'Hubungkan akun {{provider|titleize}}',
            successMessage: 'Penyedia telah ditambahkan ke akun Anda',
            removeResource: {
                title: 'Hapus akun terhubung',
                messageLine1: '{{identifier}} akan dihapus dari akun ini.',
                messageLine2: 'Anda tidak akan bisa menggunakan akun terhubung ini dan fitur terkait tidak akan berfungsi lagi.',
                successMessage: '{{connectedAccount}} telah dihapus dari akun Anda.',
            },
        },
        web3WalletPage: {
            title: 'Tambahkan dompet web3',
            subtitle__availableWallets: 'Pilih dompet web3 untuk menghubungkannya ke akun Anda.',
            subtitle__unavailableWallets: 'Tidak ada dompet web3 yang tersedia.',
            successMessage: 'Dompet telah ditambahkan ke akun Anda.',
            removeResource: {
                title: 'Hapus dompet web3', messageLine1: '{{identifier}} akan dihapus dari akun ini.',
                messageLine2: 'Anda tidak akan bisa masuk menggunakan dompet web3 ini lagi.',
                successMessage: '{{web3Wallet}} telah dihapus dari akun Anda.',
            },
        },
        passwordPage: {
            title: 'Atur kata sandi',
            changePasswordTitle: 'Ubah kata sandi',
            successMessage: 'Kata sandi Anda telah diatur.',
            changePasswordSuccessMessage: 'Kata sandi Anda telah diperbarui.',
            sessionsSignedOutSuccessMessage: 'Semua perangkat lain telah keluar.',
        },
        mfaPage: {
            title: 'Tambahkan verifikasi dua langkah',
            formHint: 'Pilih metode yang ingin ditambahkan.',
        },
        mfaTOTPPage: {
            title: 'Tambahkan aplikasi otentikator',
            verifyTitle: 'Kode verifikasi',
            verifySubtitle: 'Masukkan kode verifikasi yang dihasilkan oleh aplikasi otentikator Anda',
            successMessage:
                'Verifikasi dua langkah sekarang diaktifkan. Saat masuk, Anda perlu memasukkan kode verifikasi dari aplikasi otentikator ini sebagai langkah tambahan.',
            authenticatorApp: {
                infoText__ableToScan:
                    'Siapkan metode masuk baru di aplikasi otentikator Anda dan pindai kode QR berikut untuk menghubungkannya dengan akun Anda.',
                infoText__unableToScan: 'Siapkan metode masuk baru di aplikasi otentikator Anda dan masukkan Kunci yang diberikan di bawah.',
                inputLabel__unableToScan1:
                    'Pastikan TOTP diaktifkan, lalu selesaikan penghubungan akun Anda.',
                inputLabel__unableToScan2:
                    'Sebagai alternatif, jika otentikator Anda mendukung URI TOTP, Anda juga dapat menyalin URI lengkap.',
                buttonAbleToScan__nonPrimary: 'Pindai kode QR saja',
                buttonUnableToScan__nonPrimary: 'Tidak dapat memindai kode QR?',
            },
            removeResource: {
                title: 'Hapus verifikasi dua langkah',
                messageLine1: 'Kode verifikasi dari aplikasi otentikator ini tidak akan diperlukan lagi saat masuk.',
                messageLine2: 'Akun Anda mungkin tidak seaman sebelumnya. Apakah Anda yakin ingin melanjutkan?',
                successMessage: 'Verifikasi dua langkah melalui aplikasi otentikator telah dihapus.',
            },
        },
        mfaPhoneCodePage: {
            title: 'Tambahkan verifikasi kode SMS',
            primaryButton__addPhoneNumber: 'Tambahkan nomor telepon',
            subtitle__availablePhoneNumbers: 'Pilih nomor telepon untuk mendaftar verifikasi kode SMS dua langkah.',
            subtitle__unavailablePhoneNumbers:
                'Tidak ada nomor telepon yang tersedia untuk mendaftar verifikasi kode SMS dua langkah.',
            successMessage:
                'Verifikasi kode SMS dua langkah sekarang diaktifkan untuk nomor telepon ini. Saat masuk, Anda perlu memasukkan kode verifikasi yang dikirimkan ke nomor telepon ini sebagai langkah tambahan.',
            removeResource: {
                title: 'Hapus verifikasi dua langkah',
                messageLine1: '{{identifier}} tidak akan lagi menerima kode verifikasi saat masuk.',
                messageLine2: 'Akun Anda mungkin tidak seaman sebelumnya. Apakah Anda yakin ingin melanjutkan?',
                successMessage: 'Verifikasi kode SMS dua langkah telah dihapus.',
            },
        },
        backupCodePage: {
            title: 'Tambahkan verifikasi kode cadangan',
            title__codelist: 'Kode cadangan',
            subtitle__codelist: 'Simpan dengan aman dan jaga kerahasiaannya.',
            infoText1: 'Kode cadangan akan diaktifkan untuk akun ini.',
            infoText2: 'Jaga kerahasiaan dan simpan kode cadangan dengan aman. Anda dapat menghasilkan ulang kode cadangan jika Anda mencurigai telah terjadi pelanggaran keamanan.',
            successSubtitle: 'Anda dapat menggunakan salah satu dari ini untuk masuk ke akun Anda jika Anda kehilangan akses ke perangkat autentikasi Anda.',
            successMessage: 'Kode cadangan sekarang diaktifkan. Anda dapat menggunakan salah satu dari ini untuk masuk ke akun Anda jika Anda kehilangan akses ke perangkat autentikasi Anda. Setiap kode hanya dapat digunakan sekali.',
            actionLabel__copy: 'Salin semua',
            actionLabel__copied: 'Tersalin!',
            actionLabel__download: 'Unduh .txt',
            actionLabel__print: 'Cetak',
        },
    },
    userButton: {
        action__manageAccount: 'Kelola akun',
        action__signOut: 'Keluar',
        action__signOutAll: 'Keluar dari semua akun',
        action__addAccount: 'Tambahkan akun',
    },
    impersonationFab: {
        title: 'Masuk sebagai {{identifier}}',
        action__signOut: 'Keluar',
    },
    unstable__errors: {
        form_identifier_not_found: "Akun tidak di temukan",
        form_password_pwned:
            'Kata sandi ini ditemukan sebagai bagian dari kebocoran kata sandi dan tidak dapat digunakan, harap coba kata sandi lainnya.',
        form_username_invalid_length: '',
        form_param_format_invalid: "Format salah",
        form_password_length_too_short: "Kata sandi terlalu pendek",
        form_param_nil: '',
        form_code_incorrect: '',
        form_password_incorrect: "Kata sandi salah",
        not_allowed_access: '',
        form_identifier_exists: 'Akun sudah terdaftar',
        passwordComplexity: {
            sentencePrefix: "Kata sandi harus memiliki",
            minimumLength: "setidaknya {{length}} karakter atau lebih",
            maximumLength: 'kurang dari {{length}} karakter',
            requireNumbers: 'sebuah angka',
            requireLowercase: 'huruf kecil',
            requireUppercase: 'huruf besar',
            requireSpecialCharacter: 'karakter khusus'
        },
        zxcvbn: {
            notEnough: 'Kata sandi Anda tidak cukup kuat.',
            couldBeStronger: 'Kata sandi Anda cukup baik, tetapi bisa lebih kuat. Cobalah tambahkan karakter lebih banyak.',
            goodPassword: 'Bagus. Ini adalah kata sandi yang sangat baik.',
            warnings: {
                straightRow: 'Baris lurus pada keyboard Anda mudah ditebak.',
                keyPattern: 'Pola keyboard yang pendek mudah ditebak.',
                simpleRepeat: 'Karakter yang diulang seperti "aaa" mudah ditebak.',
                extendedRepeat: 'Pola karakter yang diulang seperti "abcabcabc" mudah ditebak.',
                sequences: 'Urutan karakter umum seperti "abc" mudah ditebak.',
                recentYears: 'Tahun-tahun terkini mudah ditebak.',
                dates: 'Tanggal mudah ditebak.',
                topTen: 'Ini adalah kata sandi yang sangat umum digunakan.',
                topHundred: 'Ini adalah kata sandi yang sering digunakan.',
                common: 'Ini adalah kata sandi yang umum digunakan.',
                similarToCommon: 'Ini mirip dengan kata sandi yang umum digunakan.',
                wordByItself: 'Kata tunggal mudah ditebak.',
                namesByThemselves: 'Nama tunggal atau nama belakang mudah ditebak.',
                commonNames: 'Nama-nama umum dan nama belakang mudah ditebak.',
                userInputs: 'Tidak boleh ada data pribadi atau terkait halaman.',
                pwned: 'Kata sandi Anda terpapar dalam pelanggaran data di Internet.',
            },
            suggestions: {
                l33t: "Hindari penggantian huruf yang mudah ditebak seperti '@' untuk 'a'.",
                reverseWords: 'Hindari penulisan terbalik dari kata-kata umum.',
                allUppercase: 'Kapitalisasi beberapa huruf, tetapi tidak semuanya.',
                capitalization: 'Kapitalisasi lebih dari huruf pertama.',
                dates: 'Hindari tanggal dan tahun yang terkait dengan Anda.',
                recentYears: 'Hindari tahun-tahun terkini.',
                associatedYears: 'Hindari tahun-tahun yang terkait dengan Anda.',
                sequences: 'Hindari urutan karakter umum.',
                repeated: 'Hindari pengulangan kata dan karakter.',
                longerKeyboardPattern: 'Gunakan pola keyboard yang lebih panjang dan ubah arah pengetikan beberapa kali.',
                anotherWord: 'Tambahkan lebih banyak kata yang kurang umum.',
                useWords: 'Gunakan beberapa kata, tetapi hindari frasa umum.',
                noNeed: 'Anda dapat membuat kata sandi yang kuat tanpa menggunakan simbol, angka, atau huruf kapital.',
                pwned: 'Jika Anda menggunakan kata sandi ini di tempat lain, sebaiknya Anda menggantinya.',
            },
        },
    }
}

const appearance: Appearance = {
    layout: {
        showOptionalFields: false,
    },
    variables: {
        fontFamily: 'var(--font-sans)',
        colorText: '#052e16',
        colorPrimary: '#15803d',
    }
}

const clerkOptions = {
    localization,
    appearance,
}

export default clerkOptions
